package tools

import (
	"github.com/labstack/echo"
    htgotts "../lib/github.com/hegedustibor/htgotts"
    "os"
	"strings"
)

func GetLastPathSegment(c echo.Context) string {
	ps := strings.Split(c.Request().RequestURI, "?")

	s := strings.Split(ps[0], "/")

	if len(s[len(s)-1]) == 0 {
		return s[len(s)-2]
	} else {
		return s[len(s)-1]
	}
}

func GetCountryCode(country string) string {
	code := ""
	switch country {
	case "afghanistan": code = "AF"
	case "iles aland": code = "AX"
	case "albanie": code = "AL"
	case "algérie": code = "DZ"
	case "samoa américaines": code = "AS"
	case "andorre": code = "AD"
	case "angola": code = "AO"
	case "anguilla": code = "AI"
	case "antarctique": code = "AQ"
	case "antigua-et-barbuda": code = "AG"
	case "argentine": code = "AR"
	case "arménie": code = "AM"
	case "aruba": code = "AW"
	case "australie": code = "AU"
	case "autriche": code = "AT"
	case "azerbaïdjan": code = "AZ"
	case "bahamas": code = "BS"
	case "bahreïn": code = "BH"
	case "bangladesh": code = "BD"
	case "barbade": code = "BB"
	case "biélorussie": code = "BY"
	case "belgique": code = "BE"
	case "belize": code = "BZ"
	case "bénin": code = "BJ"
	case "bermudes": code = "BM"
	case "bhoutan": code = "BT"
	case "bolivie": code = "BO"
	case "bosnie-herzégovine": code = "BA"
	case "botswana": code = "BW"
	case "ile bouvet": code = "BV"
	case "brésil": code = "BR"
	case "british virgin islands": code = "VG"
	case "territoire britannique de l’océan indien": code = "IO"
	case "brunei darussalam": code = "BN"
	case "bulgarie": code = "BG"
	case "burkina faso": code = "BF"
	case "burundi": code = "BI"
	case "cambodge": code = "KH"
	case "cameroun": code = "CM"
	case "canada": code = "CA"
	case "cap-vert": code = "CV"
	case "iles cayman": code = "KY"
	case "république centrafricaine": code = "CF"
	case "tchad": code = "TD"
	case "chili": code = "CL"
	case "chine": code = "CN"
	case "hong kong": code = "HK"
	case "macao": code = "MO"
	case "ile christmas": code = "CX"
	case "iles cocos": code = "CC"
	case "colombie": code = "CO"
	case "comores": code = "KM"
	case "république du congo": code = "CG"
	case "république démocratique du congo": code = "CD"
	case "iles Cook": code = "CK"
	case "costa Rica": code = "CR"
	case "côte d’Ivoire": code = "CI"
	case "croatie": code = "HR"
	case "cuba": code = "CU"
	case "chypre": code = "CY"
	case "républiquetchèque": code = "CZ"
	case "danemark": code = "DK"
	case "djibouti": code = "DJ"
	case "dominique": code = "DM"
	case "république dominicaine": code = "DO"
	case "equateur": code = "EC"
	case "egypte": code = "EG"
	case "salvador": code = "SV"
	case "guinée équatoriale": code = "GQ"
	case "erythrée": code = "ER"
	case "estonie": code = "EE"
	case "ethiopie": code = "ET"
	case "iles Falkland": code = "FK"
	case "iles Féroé": code = "FO"
	case "fidji": code = "FJ"
	case "finlande": code = "FI"
	case "france": code = "FR"
	case "guyane française": code = "GF"
	case "polynésie française": code = "PF"
	case "terres australes et antarctiques françaises": code = "TF"
	case "gabon": code = "GA"
	case "gambie": code = "GM"
	case "géorgie": code = "GE"
	case "allemagne": code = "DE"
	case "ghana": code = "GH"
	case "gibraltar": code = "GI"
	case "grèce": code = "GR"
	case "groenland": code = "GL"
	case "grenade": code = "GD"
	case "guadeloupe": code = "GP"
	case "guam": code = "GU"
	case "guatemala": code = "GT"
	case "guernesey": code = "GG"
	case "guinée": code = "GN"
	case "guinée-Bissau": code = "GW"
	case "guyane": code = "GY"
	case "haïti": code = "HT"
	case "iles heard-et-macdonald": code = "HM"
	case "saint-siège (vatican)": code = "VA"
	case "honduras": code = "HN"
	case "hongrie": code = "HU"
	case "islande": code = "IS"
	case "inde": code = "IN"
	case "indonésie": code = "ID"
	case "iran": code = "IR"
	case "irak": code = "IQ"
	case "irlande": code = "IE"
	case "ile de Man": code = "IM"
	case "israël": code = "IL"
	case "italie": code = "IT"
	case "jamaïque": code = "JM"
	case "japon": code = "JP"
	case "jersey": code = "JE"
	case "jordanie": code = "JO"
	case "kazakhstan": code = "KZ"
	case "kenya": code = "KE"
	case "kiribati": code = "KI"
	case "corée du Nord": code = "KP"
	case "corée du Sud": code = "KR"
	case "koweït": code = "KW"
	case "kirghizistan": code = "KG"
	case "laos": code = "LA"
	case "lettonie": code = "LV"
	case "liban": code = "LB"
	case "lesotho": code = "LS"
	case "libéria": code = "LR"
	case "libye": code = "LY"
	case "liechtenstein": code = "LI"
	case "lituanie": code = "LT"
	case "luxembourg": code = "LU"
	case "macédoine": code = "MK"
	case "madagascar": code = "MG"
	case "malawi": code = "MW"
	case "malaisie": code = "MY"
	case "maldives": code = "MV"
	case "mali": code = "ML"
	case "malte": code = "MT"
	case "iles marshall": code = "MH"
	case "martinique": code = "MQ"
	case "mauritanie": code = "MR"
	case "maurice": code = "MU"
	case "mayotte": code = "YT"
	case "mexique": code = "MX"
	case "micronésie": code = "FM"
	case "moldavie": code = "MD"
	case "monaco": code = "MC"
	case "mongolie": code = "MN"
	case "monténégro": code = "ME"
	case "montserrat": code = "MS"
	case "maroc": code = "MA"
	case "mozambique": code = "MZ"
	case "myanmar": code = "MM"
	case "namibie": code = "NA"
	case "nauru": code = "NR"
	case "népal": code = "NP"
	case "pays-bas": code = "NL"
	case "nouvelle-calédonie": code = "NC"
	case "nouvelle-zélande": code = "NZ"
	case "nicaragua": code = "NI"
	case "niger": code = "NE"
	case "nigeria": code = "NG"
	case "niue": code = "NU"
	case "ile Norfolk": code = "NF"
	case "iles mariannes du nord": code = "MP"
	case "norvège": code = "NO"
	case "oman": code = "OM"
	case "pakistan": code = "PK"
	case "palau": code = "PW"
	case "palestine": code = "PS"
	case "panama": code = "PA"
	case "papouasie-nouvelle-guinée": code = "PG"
	case "paraguay": code = "PY"
	case "pérou": code = "PE"
	case "philippines": code = "PH"
	case "pitcairn": code = "PN"
	case "pologne": code = "PL"
	case "portugal": code = "PT"
	case "puerto Rico": code = "PR"
	case "qatar": code = "QA"
	case "réunion": code = "RE"
	case "roumanie": code = "RO"
	case "russie": code = "RU"
	case "rwanda": code = "RW"
	case "saint-narthélemy": code = "BL"
	case "sainte-hélène": code = "SH"
	case "saint-kitts-et-nevis": code = "KN"
	case "sainte-Lucie": code = "LC"
	case "saint-martin (partie française)": code = "MF"
	case "saint-martin (partie néerlandaise)": code = "SX"
	case "saint-pierre-et-miquelon": code = "PM"
	case "saint-vincent-et-les grenadines": code = "VC"
	case "samoa": code = "WS"
	case "saint-Marin": code = "SM"
	case "sao tomé-et-principe": code = "ST"
	case "arabie saoudite": code = "SA"
	case "sénégal": code = "SN"
	case "serbie": code = "RS"
	case "seychelles": code = "SC"
	case "sierra leone": code = "SL"
	case "singapour": code = "SG"
	case "slovaquie": code = "SK"
	case "slovénie": code = "SI"
	case "iles Salomon": code = "SB"
	case "somalie": code = "SO"
	case "afrique du sud": code = "ZA"
	case "géorgie du sud et les îles sandwich du sud": code = "GS"
	case "sud-soudan": code = "SS"
	case "espagne": code = "ES"
	case "sri lanka": code = "LK"
	case "soudan": code = "SD"
	case "suriname": code = "SR"
	case "svalbard et jan mayen": code = "SJ"
	case "eswatini": code = "SZ"
	case "suède": code = "SE"
	case "suisse": code = "CH"
	case "syrie": code = "SY"
	case "taiwan": code = "TW"
	case "tadjikistan": code = "TJ"
	case "tanzanie": code = "TZ"
	case "thaïlande": code = "TH"
	case "timor-Leste": code = "TL"
	case "togo": code = "TG"
	case "tokelau": code = "TK"
	case "tonga": code = "TO"
	case "trinité-et-tobago": code = "TT"
	case "tunisie": code = "TN"
	case "turquie": code = "TR"
	case "turkménistan": code = "TM"
	case "iles turques-et-caïques": code = "TC"
	case "tuvalu": code = "TV"
	case "ouganda": code = "UG"
	case "ukraine": code = "UA"
	case "emirats arabes unis": code = "AE"
	case "royaume-uni": code = "GB"
	case "etats-Unis": code = "US"
	case "iles mineures éloignées des états-Unis": code = "UM"
	case "uruguay": code = "UY"
	case "ouzbékistan": code = "UZ"
	case "vanuatu": code = "VU"
	case "venezuela": code = "VE"
	case "viêt Nam": code = "VN"
	case "iles vierges américaines": code = "VI"
	case "wallis-et-futuna": code = "WF"
	case "sahara occidental": code = "EH"
	case "yémen": code = "YE"
	case "zambie": code = "ZM"
	case "zimbabwe": code = "ZW"
	}

	return code
}



func GetMP3SoundFromText(text string, language string) {
	speech := htgotts.Speech{Folder: os.Getenv("AUDIO_FOLDER") , Language: language}
	_ = speech.Speak(text)
}
